name: Create and publish a pnpm node_modules tarball
# Original author: Arthur Zamarin
# modified by: liuyujielol
description: Create a Gentoo pnpm node_modules tarball and attach it to a release
inputs:
  tag:
    description: Tag to create release on
    default: ${{ github.ref_name }}
  vendor-dir:
    description: Top level dir name inside source archive
  dist-filename:
    description: The name of distribution file (e.g. foo-1.2.3-node_modules.tar.xz)
    default: ${{ github.event.repository.name }}-${{ github.ref_name }}
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-node@v6
      with:
        node-version: 'lastest' # maybe not ideal
        check-latest: true

    - name: Collect node_modules
      shell: bash
      env:
        store-dir: "/tmp/node-modules"
      run: |
        find . -iname 'package.json' -type f -exec dirname {} \; | while read store-dir; do
          echo "::group::Processing ${store-dir}/package.json"
          pushd "${store-dir}" >&/dev/null || exit 1
          pnpm install --frozen-lockfile || exit 1
          popd >&/dev/null || exit 1
          echo "::endgroup::"
        done

    - name: Create a node_modules tarball
      shell: bash
      env:
        XZ_OPT: "-T0 -9e"
      run: |
        echo "::group::Creating dist tarball ${{ inputs.dist-filename }}-node_modules.tar.xz"
        #find "/tmp/node-modules/" -type f -name '*.zip' -delete || exit 1
        LC_ALL=C TZ=UTC tar -C /tmp \
          --mtime="${SOURCE_DATE_EPOCH:-1970-01-01}" --sort=name --owner=250 --group=250 \
          -acf "${{ inputs.dist-filename }}-node_modules.tar.xz" node-modules || exit 1
        echo "::endgroup::"

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        body:
        files: |
          ${{ inputs.dist-filename }}-node_modules.tar.xz
        tag_name: ${{ inputs.tag }}
        fail_on_unmatched_files: true
